spring.application.name=groq


spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=meta-llama/llama-4-scout-17b-16e-instruct
spring.ai.openai.chat.options.temperature=0.7

#spring.ai.openai.chat.options.model=gpt-4o
#spring.ai.openai.chat.options.model=gpt-3.5-turbo-0125

# virtual thread
spring.threads.virtual.enabled=true

# ollama run bespoke-minicheck
spring.ai.ollama.chat.model=bespokeai/minicheck
spring.ai.ollama.chat.temperature=0.1
